/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#eff1f3',
        background: '#f7f9fb',
        'inverse-primary': '#84cfff',
        'inverse-surface': '#2d3133',
        surface: '#f7f9fb',
        'surface-tint': '#00658e',
        'error-container': '#ffdad6',
        outline: '#6e7881',
        'on-primary-container': '#00334a',
        'on-secondary-fixed': '#0d1c2f',
        'on-secondary': '#ffffff',
        'surface-dim': '#d8dadc',
        'surface-container-high': '#e6e8ea',
        'surface-variant': '#e0e3e5',
        'on-primary': '#ffffff',
        'primary-fixed-dim': '#84cfff',
        'on-tertiary-fixed': '#001f26',
        'surface-container-low': '#f2f4f6',
        'tertiary-fixed-dim': '#4cd7f6',
        'on-surface-variant': '#3e4850',
        'secondary-container': '#d5e3fd',
        'on-tertiary-container': '#00343f',
        'on-error': '#ffffff',
        'on-primary-fixed': '#001e2e',
        'primary-fixed': '#c7e7ff',
        'secondary-fixed-dim': '#b9c7e0',
        'surface-container': '#eceef0',
        'primary-container': '#00a1e0',
        secondary: '#515f74',
        'on-secondary-fixed-variant': '#3a485c',
        'on-background': '#191c1e',
        'on-surface': '#191c1e',
        'on-error-container': '#93000a',
        primary: '#00658e',
        'tertiary-container': '#00a5c1',
        'on-tertiary-fixed-variant': '#004e5c',
        'surface-bright': '#f7f9fb',
        'tertiary-fixed': '#acedff',
        'secondary-fixed': '#d5e3fd',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed-variant': '#004c6c',
        'on-tertiary': '#ffffff',
        'on-secondary-container': '#57657b',
        error: '#ba1a1a',
        tertiary: '#00687a',
        'surface-container-highest': '#e0e3e5',
        'outline-variant': '#bdc8d1',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        unit: '8px',
        'section-gap': '80px',
        'margin-mobile': '16px',
        'container-max': '1280px',
        gutter: '24px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        'headline-md': ['Inter'],
        'headline-lg': ['Inter'],
        'body-lg': ['Inter'],
        'label-mono': ['JetBrains Mono', 'monospace'],
        'headline-xl-mobile': ['Inter'],
        'body-md': ['Inter'],
        'headline-xl': ['Inter'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-mono': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-xl-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
      },
    },
  },
  plugins: [],
}
